version: '3'

services:
  reviewserver:
    build: .
    depends_on:
      - 'database'
    ports:
      - '3000:3000'

  database:
    build: database/
    ports:
      - '3306:3306'

#     database:
 #       image: mysql
  #      command: --default-authentication-plugin=mysql_native_password
  #      restart: always
   #     environment:
    #      MYSQL_ROOT_PASSWORD: ennui
     #     MYSQL_DATABASE: etsy